"""Added new fields

Revision ID: 20f2310f8b31
Revises: de7072fb16df
Create Date: 2025-03-17 16:26:02.175664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f2310f8b31'
down_revision: Union[str, None] = 'de7072fb16df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('institution', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'designation')
    op.drop_column('users', 'institution')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
