"""Added new fields

Revision ID: 26974f6bfd67
Revises: d17da7d75241
Create Date: 2025-03-10 16:34:25.981809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26974f6bfd67'
down_revision: Union[str, None] = 'd17da7d75241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('gene_ontology', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'gene_ontology')
    # ### end Alembic commands ###
