"""Added column data field

Revision ID: 2fcbe0879d4a
Revises: 0089349c2169
Create Date: 2025-02-20 14:17:34.496974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcbe0879d4a'
down_revision: Union[str, None] = '0089349c2169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('column_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'column_data')
    # ### end Alembic commands ###
