"""Added new fields

Revision ID: 5d9b2bfc53b7
Revises: 41989ca4c1b4
Create Date: 2025-02-24 11:38:23.718553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9b2bfc53b7'
down_revision: Union[str, None] = '41989ca4c1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lable_free_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lable_free_analysis_id'), 'lable_free_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_lable_free_analysis_user_id'), 'lable_free_analysis', ['user_id'], unique=False)
    op.add_column('analysis', sa.Column('batch_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'batch_data')
    op.drop_index(op.f('ix_lable_free_analysis_user_id'), table_name='lable_free_analysis')
    op.drop_index(op.f('ix_lable_free_analysis_id'), table_name='lable_free_analysis')
    op.drop_table('lable_free_analysis')
    # ### end Alembic commands ###
