"""Added some fields

Revision ID: 643d633eea8b
Revises: b8a0d250d6bf
Create Date: 2025-02-21 16:09:14.022817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643d633eea8b'
down_revision: Union[str, None] = 'b8a0d250d6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('pv_method', sa.String(length=50), nullable=True))
    op.add_column('analysis', sa.Column('pv_cutoff', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('ratio_up', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('log2_cut', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('control_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'control_name')
    op.drop_column('analysis', 'log2_cut')
    op.drop_column('analysis', 'ratio_up')
    op.drop_column('analysis', 'pv_cutoff')
    op.drop_column('analysis', 'pv_method')
    # ### end Alembic commands ###
