"""Added column_data nullable

Revision ID: b8a0d250d6bf
Revises: 2fcbe0879d4a
Create Date: 2025-02-20 14:18:30.315777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a0d250d6bf'
down_revision: Union[str, None] = '2fcbe0879d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
