"""Added new fields

Revision ID: d17da7d75241
Revises: 5d9b2bfc53b7
Create Date: 2025-02-25 11:55:25.989233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17da7d75241'
down_revision: Union[str, None] = '5d9b2bfc53b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('ratio_or_log2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'ratio_or_log2')
    # ### end Alembic commands ###
