"""Make no_of_batches nullable

Revision ID: d921104adfda
Revises: d895045075ce
Create Date: 2025-02-07 14:33:13.320501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd921104adfda'
down_revision: Union[str, None] = 'd895045075ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('file_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'file_type')
    # ### end Alembic commands ###
