"""Added new fields

Revision ID: de7072fb16df
Revises: b93dc4c29b32
Create Date: 2025-03-14 15:22:03.940860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7072fb16df'
down_revision: Union[str, None] = 'b93dc4c29b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vizualization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('viz_type', sa.String(length=50), nullable=True),
    sa.Column('viz_data', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vizualization_id'), 'vizualization', ['id'], unique=False)
    op.create_index(op.f('ix_vizualization_user_id'), 'vizualization', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vizualization_user_id'), table_name='vizualization')
    op.drop_index(op.f('ix_vizualization_id'), table_name='vizualization')
    op.drop_table('vizualization')
    # ### end Alembic commands ###
